from cowskit.encodings.encoding import Encoding
from cowskit.encodings.encoding_binary import BinaryEncoding
from cowskit.encodings.encoding_amplitude import AmplitudeEncoding
from cowskit.encodings.encoding_angle import AngleEncoding